function gui_star
folder = 'C:\Users\Mörököllit\Pictures\2018-10-29 leikkimokki\';

% Make figure, axes and plot map
hfig = figure('Position',[100,100,1400,700]);
handleaxes = axes('Parent', hfig,...
    'Units','Pixels',...
    'Position',[350,100,1000,550]);

file_list = [];
path_list = [];
h_load = uicontrol('Parent',hfig,...
    'Style','pushbutton',...
    'String', 'load images', ...
    'Value', 0, ...
    'Position', [50 500, 100, 100], ...
    'Callback', @(src,eventdata)load_callback(src,eventdata) );

% h_load = uicontrol('Parent',hfig,...
%     'Style','pushbutton',...
%     'String', 'load images', ...
%     'Value', 0, ...
%     'Position', [50 500, 100, 100], ...
%     'Callback', @(src,eventdata)load_callback(src,eventdata) );

    % Load images Callback
    function load_callback(src,event)
        [file_list, path_list] = uigetfile(fullfile(folder, '.jpg'), ...
            'All Files (*.*)','MultiSelect','on');
use        imshow(fullfile(path_list{1},file_list{1}))
    end
end
